spring:
  application:
    name: veiculos-api

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/veiculos}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate.format_sql: true
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.xml

